### ISSUE TITLE
请问可以通过shadowrocket实现吗？

### ISSUE THREAD

**Issue by liujf916** [CharlieDijkstra/xiaoyuankousuan_ios#1]
小火箭的图形化界面过于简陋似乎无法实现。需要自己写模块，但是模块的语法我不太懂。

**Comment by CharlieDijkstra** [comment]
> 小火箭的图形化界面过于简陋似乎无法实现。需要自己写模块，但是模块的语法我不太懂。

可以实现的，模块那一部分我也不清楚，稍后会在readme中更新小火箭使用脚本实现的方法

**Comment by CharlieDijkstra** [comment]
> > > 小火箭的图形化界面过于简陋似乎无法实现。需要自己写模块，但是模块的语法我不太懂。
> > 
> > 
> > 可以实现的，模块那一部分我也不清楚，稍后会在readme中更新小火箭使用脚本实现的方法
> 
> 似乎已经抓不到js文件了🤔

js文件能够正常抓取，小火箭需要打开https解密，目前问题是pk前的加载ui异常
